# Generated by Django 5.1.7 on 2025-03-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='componente',
            field=models.CharField(default=False, max_length=300),
            preserve_default=False,
        ),
    ]
