# Generated by Django 5.1.7 on 2025-03-20 23:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_logmessage_componente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_limpio', models.BooleanField(default=False)),
                ('se_ruteo', models.BooleanField(default=False)),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date logged')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='App1.station')),
            ],
        ),
    ]
