# Generated by Django 5.1.7 on 2025-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_station_maintenancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='se_limpio',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='se_ruteo',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='mantenimiento_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='nombre_ingeniero',
            field=models.CharField(default='Ingeniero', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='nombre_tecnico',
            field=models.CharField(default='Tecnico', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='unidad_de_trabajo',
            field=models.CharField(default='Unidad de Trabajo', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='week_number',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
