# Generated by Django 5.1.7 on 2025-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_remove_maintenancerecord_se_limpio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='comentarios',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='nombre_ingeniero',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='nombre_tecnico',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='unidad_de_trabajo',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
