# Generated by Django 5.1.7 on 2025-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_maintenancerecord_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='mantenimiento_completado',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo')], default='Preventivo', max_length=20),
        ),
    ]
