# Generated by Django 5.1.7 on 2025-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_remove_maintenancerecord_mantenimiento_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='unidad_de_trabajo',
            field=models.CharField(choices=[('SPSF', 'tapes'), ('tapes', 'SPSF')], default='--', max_length=100),
        ),
    ]
