# Generated by Django 5.1.7 on 2025-04-03 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_mantenimientochecklist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceChecklistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_records', to='App1.maintenancerecord')),
            ],
        ),
    ]
