# Generated by Django 5.1.7 on 2025-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_maintenancechecklistrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
