# Generated by Django 5.1.7 on 2025-04-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_alter_maintenancerecord_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
