# Generated by Django 5.1.7 on 2025-05-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_maintenancerecord_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mantenimientos/'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='unidad_de_trabajo',
            field=models.CharField(choices=[('TAPES', 'TAPES'), ('SPSF', 'SPSF')], default='--', max_length=100),
        ),
    ]
