# Generated by Django 5.2 on 2025-05-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_maintenancerecord_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='aprobado',
            new_name='estado',
        ),
    ]
