# Generated by Django 5.1.7 on 2025-05-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_maintenancerecord_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='comentarios',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
    ]
