# Generated by Django 5.2 on 2025-05-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_rename_aprobado_maintenancerecord_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='estado',
            new_name='aprobado',
        ),
    ]
