# Generated by Django 5.1.7 on 2025-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_alter_maintenancerecord_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='miniwhite_valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
