# Generated by Django 5.1.7 on 2025-05-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_maintenancerecord_miniwhite_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='miniwhite_valor',
            new_name='cells_active',
        ),
    ]
