# Generated by Django 5.1.7 on 2025-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_rename_miniwhite_valor_maintenancerecord_cells_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='unidad_de_trabajo',
            field=models.CharField(choices=[('TAPES', 'TAPES'), ('SPSF', 'SPSF'), ('MiniWhite', 'MiniWhite')], default='--', max_length=100),
        ),
    ]
